version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      # KAFKA_LISTENERS: LISTENER_FRED://0.0.0.0:9092,PLAINTEXT://kafka:29092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,LISTENER_FRED://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT,LISTENER_FRED
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper

  buffered_service:
    image: buffered_server
    container_name: buffer_request
    build:
      context: ../
      dockerfile: build/Dockerfile
    command: ./buffer -env docker
    ports:
      - 9000:9000
    links:
      - kafka-ui

  # consumer:
  #   build:
  #     context: .
  #     dockerfile: consumer/Dockerfile
  #   ports:
  #     - 8081:8080
  #   links:
  #     - kafka-ui
